/* Portable contract test of extracted production functions, not a Quartz
 * implementation or an interactive editor test. No system input is posted. */
#include <assert.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef uint16_t CGKeyCode;
typedef uint16_t UniChar;
typedef size_t UniCharCount;
typedef uint64_t CGEventFlags;
enum {
    kCGEventSourceStatePrivate = -1,
    kCGEventSourceStateCombinedSessionState = 0,
    kCGEventSourceStateHIDSystemState = 1,
    kCGHIDEventTap = 0,
    kVK_RightArrow = 124
};
#define kCGEventFlagMaskShift (UINT64_C(1) << 17)
#define kCGEventFlagMaskControl (UINT64_C(1) << 18)
#define kCGEventFlagMaskAlternate (UINT64_C(1) << 19)
#define kCGEventFlagMaskCommand (UINT64_C(1) << 20)

typedef struct FakeSource { int kind; int state; } *CGEventSourceRef;
typedef struct FakeEvent {
    int kind;
    int source_state;
    CGKeyCode key;
    bool down;
    CGEventFlags flags;
    bool flags_explicit;
    UniChar units[32];
    size_t length;
} *CGEventRef;

static bool trusted = true, secure_input;
static CGEventFlags hardware_flags, combined_flags;
static int queried_state, allocation_count, fail_allocation, live_allocations;
static int64_t clipboard_revision = 17;
static struct FakeEvent posted[4096];
static size_t post_count;

static bool AXIsProcessTrusted(void) { return trusted; }
static bool IsSecureEventInputEnabled(void) { return secure_input; }
static CGEventFlags CGEventSourceFlagsState(int state) {
    queried_state = state;
    return state == kCGEventSourceStateHIDSystemState ? hardware_flags : combined_flags;
}
static void *allocate(size_t size) {
    allocation_count++;
    if (allocation_count == fail_allocation) return NULL;
    void *result = calloc(1, size);
    assert(result != NULL);
    live_allocations++;
    return result;
}
static CGEventSourceRef CGEventSourceCreate(int state) {
    CGEventSourceRef source = allocate(sizeof(*source));
    if (source != NULL) { source->kind = 1; source->state = state; }
    return source;
}
static CGEventRef CGEventCreateKeyboardEvent(CGEventSourceRef source, CGKeyCode key, bool down) {
    CGEventRef event = allocate(sizeof(*event));
    if (event != NULL) {
        event->kind = 2;
        event->source_state = source == NULL ? kCGEventSourceStateCombinedSessionState : source->state;
        event->key = key;
        event->down = down;
        event->flags = event->source_state == kCGEventSourceStatePrivate ? 0 : combined_flags;
    }
    return event;
}
static void CGEventSetFlags(CGEventRef event, CGEventFlags flags) {
    assert(event != NULL);
    event->flags = flags;
    event->flags_explicit = true;
}
static void CGEventKeyboardSetUnicodeString(CGEventRef event, UniCharCount count, const UniChar *units) {
    assert(event != NULL && count <= 32);
    memcpy(event->units, units, count * sizeof(UniChar));
    event->length = count;
}
static void CGEventPost(int tap, CGEventRef event) {
    assert(tap == kCGHIDEventTap && post_count < 4096);
    posted[post_count++] = *event;
    /* Model a combined-session table contaminated by prior synthetic flags.
     * Hardware flags are an independent input in this contract test. */
    combined_flags = event->flags;
}
static void CFRelease(void *object) {
    assert(object != NULL && live_allocations > 0);
    live_allocations--;
    free(object);
}
static int64_t ct_macos_clipboard_change_count(void) { return clipboard_revision; }

/* Generated by verify_code_navigation.py from the actual .m source. */
#include "native_keyboard_under_test.inc"

static int failures, tests;
#define CHECK(condition) do { if (!(condition)) { \
    fprintf(stderr, "FAIL %s:%d: %s\n", __func__, __LINE__, #condition); \
    failures++; return; } } while (0)
static void reset(void) {
    assert(live_allocations == 0);
    trusted = true; secure_input = false;
    hardware_flags = 0; combined_flags = 0; queried_state = -100;
    allocation_count = 0; fail_allocation = 0; post_count = 0;
    memset(posted, 0, sizeof(posted));
}
static void check_private_events(void) {
    for (size_t i = 0; i < post_count; i++) {
        CHECK(posted[i].source_state == kCGEventSourceStatePrivate);
        CHECK(posted[i].flags_explicit);
        /* No events press or release physical modifier keys. */
        CHECK(posted[i].key < 54 || posted[i].key > 62);
    }
}
static void navigation_sequence(void) {
    reset(); combined_flags = kCGEventFlagMaskShift;
    CHECK(ct_macos_post_cursor_right_to_line_end() == 1);
    CHECK(post_count == 4 && live_allocations == 0);
    const CGEventFlags expected[4] = {0, 0, kCGEventFlagMaskCommand, 0};
    for (size_t i = 0; i < 4; i++) {
        CHECK(posted[i].key == kVK_RightArrow);
        CHECK(posted[i].down == (i % 2 == 0));
        CHECK(posted[i].flags == expected[i]);
    }
    check_private_events();
}
static void ignores_synthetic_session_flags(void) {
    reset(); combined_flags = kCGEventFlagMaskCommand;
    CHECK(ct_macos_modifier_flags() == 0);
    CHECK(queried_state == kCGEventSourceStateHIDSystemState);
}
static void first_navigation_does_not_poison_next_check(void) {
    reset();
    CHECK(ct_macos_post_cursor_right_to_line_end() == 1);
    CHECK(ct_macos_modifier_flags() == 0);
    CHECK(ct_macos_post_return() == 1);
    const uint16_t next = 'i';
    CHECK(ct_macos_post_unicode(&next, 1) == 1);
    CHECK(post_count == 8);
    for (size_t i = 4; i < 8; i++) CHECK(posted[i].flags == 0);
    check_private_events();
}
static void preserves_physical_modifiers(void) {
    const CGEventFlags masks[] = {kCGEventFlagMaskShift, kCGEventFlagMaskControl,
        kCGEventFlagMaskAlternate, kCGEventFlagMaskCommand};
    for (size_t i = 0; i < sizeof(masks) / sizeof(masks[0]); i++) {
        reset(); hardware_flags = masks[i]; combined_flags = 0;
        CHECK(ct_macos_modifier_flags() == masks[i]);
        CHECK(post_count == 0); /* The observer never releases a physical key. */
        /* Force a synthetic action solely to check source independence. The
         * production coordinator must (and still does) reject held modifiers. */
        CHECK(ct_macos_post_cursor_right_to_line_end() == 1);
        CHECK(ct_macos_modifier_flags() == masks[i]);
        CHECK(hardware_flags == masks[i]);
        check_private_events();
    }
}
static void unicode_has_no_inherited_flags(void) {
    reset(); combined_flags = kCGEventFlagMaskCommand | kCGEventFlagMaskShift;
    const uint16_t value = 0x4E2D;
    CHECK(ct_macos_post_unicode(&value, 1) == 1);
    CHECK(post_count == 2 && live_allocations == 0);
    CHECK(posted[0].length == 1 && posted[0].units[0] == value);
    CHECK(posted[1].length == 0);
    CHECK(posted[0].flags == 0 && posted[1].flags == 0);
    check_private_events();
}
static void unicode_surrogates_and_bound(void) {
    reset(); const uint16_t value[2] = {0xD83D, 0xDE00};
    CHECK(ct_macos_post_unicode(value, 2) == 1);
    CHECK(posted[0].length == 2);
    CHECK(memcmp(posted[0].units, value, sizeof(value)) == 0);
    reset(); uint16_t maximum[32];
    for (size_t i = 0; i < 32; i++) maximum[i] = (uint16_t)('a' + (i % 26));
    CHECK(ct_macos_post_unicode(maximum, 32) == 1);
    CHECK(posted[0].length == 32);
    CHECK(memcmp(posted[0].units, maximum, sizeof(maximum)) == 0);
}
static void unicode_rejects_invalid_arguments(void) {
    reset(); const uint16_t value = 'a';
    CHECK(ct_macos_post_unicode(NULL, 1) == 0);
    CHECK(ct_macos_post_unicode(&value, 0) == 0);
    CHECK(ct_macos_post_unicode(&value, 33) == 0);
    CHECK(post_count == 0 && allocation_count == 0 && live_allocations == 0);
}
static void denied_permission_posts_nothing(void) {
    reset(); trusted = false; const uint16_t value = 'a';
    CHECK(ct_macos_post_cursor_right_to_line_end() == 0);
    CHECK(ct_macos_post_unicode(&value, 1) == 0);
    CHECK(ct_macos_post_return() == 0);
    CHECK(ct_macos_post_paste(clipboard_revision) == 0);
    CHECK(post_count == 0 && allocation_count == 0);
}
static void secure_input_posts_nothing(void) {
    reset(); secure_input = true; const uint16_t value = 'a';
    CHECK(ct_macos_secure_input_enabled() == 1);
    CHECK(ct_macos_post_cursor_right_to_line_end() == 0);
    CHECK(ct_macos_post_unicode(&value, 1) == 0);
    CHECK(ct_macos_post_tab() == 0);
    CHECK(ct_macos_post_paste(clipboard_revision) == 0);
    CHECK(post_count == 0 && allocation_count == 0);
}
static void navigation_allocation_failures_are_atomic(void) {
    for (int i = 1; i <= 5; i++) {
        reset(); fail_allocation = i;
        int result = ct_macos_post_cursor_right_to_line_end();
        CHECK(live_allocations == 0);
        CHECK(result == 0 && post_count == 0);
    }
}
static void simple_key_allocation_failures_are_atomic(void) {
    for (int i = 1; i <= 3; i++) {
        reset(); fail_allocation = i;
        int result = ct_macos_post_return();
        CHECK(live_allocations == 0);
        CHECK(result == 0 && post_count == 0);
    }
}
static void unicode_allocation_failures_are_atomic(void) {
    for (int i = 1; i <= 3; i++) {
        reset(); fail_allocation = i; const uint16_t value = 'a';
        int result = ct_macos_post_unicode(&value, 1);
        CHECK(live_allocations == 0);
        CHECK(result == 0 && post_count == 0);
    }
}
static void controls_remain_one_balanced_pair(void) {
    reset();
    CHECK(ct_macos_post_return() == 1);
    CHECK(ct_macos_post_tab() == 1);
    CHECK(ct_macos_post_backspace() == 1);
    CHECK(ct_macos_post_cursor_right() == 1);
    CHECK(post_count == 8 && live_allocations == 0);
    const CGKeyCode keys[4] = {36, 48, 51, kVK_RightArrow};
    for (size_t i = 0; i < 8; i++) {
        CHECK(posted[i].key == keys[i / 2]);
        CHECK(posted[i].down == (i % 2 == 0));
        CHECK(posted[i].flags == 0);
    }
    check_private_events();
}
static void paste_keeps_revision_guard_and_cleans_own_flags(void) {
    reset();
    CHECK(ct_macos_post_paste(clipboard_revision + 1) == -1);
    CHECK(post_count == 0 && allocation_count == 0);
    CHECK(ct_macos_post_paste(clipboard_revision) == 1);
    CHECK(post_count == 2 && live_allocations == 0);
    CHECK(posted[0].key == 9 && posted[1].key == 9);
    CHECK(posted[0].flags == kCGEventFlagMaskCommand);
    CHECK(posted[1].flags == 0);
    CHECK(ct_macos_modifier_flags() == 0);
    check_private_events();
}
static void repeated_navigation_reaches_tail(void) {
    reset(); const uint16_t value = 'i';
    for (size_t i = 0; i < 100; i++) {
        CHECK(ct_macos_post_cursor_right_to_line_end() == 1);
        CHECK(ct_macos_modifier_flags() == 0);
        CHECK(ct_macos_post_return() == 1);
        CHECK(ct_macos_post_unicode(&value, 1) == 1);
    }
    CHECK(post_count == 800 && live_allocations == 0);
    check_private_events();
}
#define RUN(test) do { tests++; test(); } while (0)
int main(void) {
    RUN(navigation_sequence);
    RUN(ignores_synthetic_session_flags);
    RUN(first_navigation_does_not_poison_next_check);
    RUN(preserves_physical_modifiers);
    RUN(unicode_has_no_inherited_flags);
    RUN(unicode_surrogates_and_bound);
    RUN(unicode_rejects_invalid_arguments);
    RUN(denied_permission_posts_nothing);
    RUN(secure_input_posts_nothing);
    RUN(navigation_allocation_failures_are_atomic);
    RUN(simple_key_allocation_failures_are_atomic);
    RUN(unicode_allocation_failures_are_atomic);
    RUN(controls_remain_one_balanced_pair);
    RUN(paste_keeps_revision_guard_and_cleans_own_flags);
    RUN(repeated_navigation_reaches_tail);
    printf("native_contract_tests=%d failures=%d scope=mock_quartz_not_interactive\n", tests, failures);
    return failures == 0 ? EXIT_SUCCESS : EXIT_FAILURE;
}
