#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def replace_once(relative: str, old: str, new: str) -> None:
    path = ROOT / relative
    text = path.read_text(encoding="utf-8")
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{relative}: expected one replacement, found {count}")
    path.write_text(text.replace(old, new), encoding="utf-8")


replace_once(
    "docs/INJECTION_ENGINE.md",
    """  Python-style triple-quoted runs (`\"\"\"` and `'''`) are typed explicitly at
  both boundaries because editors do not reliably synthesize a skippable
  three-character pair. Markdown triple-backtick fences are also typed
  literally; code inside a fence remains subject to normal Code-mode pair
  handling. Ordinary brackets inside a normal single- or double-quoted string
  are kept in the pair queue too, so any generated inner closers are consumed
  before the string boundary;
  their source characters remain literal. Recognized comments remain literal;
  no clipboard revision witness is used.
""",
    """  Pair-aware behavior is restricted to `()`, `{}`, `[]`, `\"\"`, and `''`.
  Brackets inside ordinary quoted strings and recognized comments are typed
  literally and never enter the pair stack; only the generated closing quote
  is skipped for an ordinary string. Python-style triple-quoted runs
  (`\"\"\"` and `'''`) are typed explicitly at both boundaries because editors
  do not reliably synthesize a skippable three-character pair. Markdown
  triple-backtick fences and single backticks are literal; code inside a fence
  remains subject to normal Code-mode pair handling. The line-leading closer
  rule is also evaluated at a `//` comment boundary before Return is emitted.
  No clipboard revision witness is used.
""",
)

replace_once(
    "docs/PRODUCT.md",
    """`code` is an explicit keyboard mode for source code and structured text. It
skips leading spaces and Tabs at each normal-code line so the editor can supply
indentation, types opening `()`, `{}`, `[]`, and quotes, then uses a cursor-right
action to pass over matching pairs already generated by the editor. When a
matching closer is the first non-indentation character on its source line,
Code mode does not insert a redundant line break before the editor's existing
closing line: it crosses that line boundary and moves to the generated line's
end with right-arrow navigation. Comment delimiters remain literal. Python-style
triple-quoted boundaries (`\"\"\"` and `'''`) are typed explicitly and do not use
cursor-right because editors do not reliably auto-complete them. Code mode
also types Markdown triple-backtick fences literally and keeps pair handling
active inside them. It assumes the destination editor's ordinary auto-pair and
auto-indent behavior is enabled. Code actions are dispatched in source order
with a short bounded settle interval and an additional navigation-only barrier
so asynchronous editor auto-pair and auto-indent updates are not overtaken by
the next action. It does not read
target content or claim editor-specific formatting semantics. Ordinary
brackets generated inside a normal single- or double-quoted string are also
consumed in source order before the string boundary; the source characters
remain literal.
""",
    """`code` is an explicit keyboard-only mode for source code and structured text.
It is separate from Keyboard and Clipboard delivery and never invokes Paste.
It skips leading spaces and Tabs at each normal-code line so the editor can
supply indentation. Pair-aware behavior is limited to `()`, `{}`, `[]`, `\"\"`,
and `''`: openers are typed and a matching source closer uses Right Arrow to
pass over the editor-generated closer. Brackets inside strings and recognized
comments are always typed literally. When a matching closer is the first
non-indentation character on its source line, including immediately after a
`//` comment, Code mode avoids a redundant line break and crosses the existing
editor-generated closing line. Python-style triple-quoted boundaries
(`\"\"\"` and `'''`) are typed explicitly. Markdown triple-backtick fences and
single backticks are literal. Actions remain strict FIFO with bounded settle
barriers so auto-pair and auto-indent updates complete before dependent
navigation. Code mode never reads target content or claims editor-specific
formatting semantics.
""",
)

replace_once(
    "docs/ARCHITECTURE.md",
    """Python-style triple-quoted runs (`\"\"\"` and `'''`) are emitted as
explicit atoms at both boundaries and never use cursor-right because editors
do not reliably generate their three-character closing pair. Brackets and
quotes inside recognized strings and comments remain literal. If the
destination editor also generates ordinary bracket pairs inside a normal
single- or double-quoted string, the plan tracks and consumes those generated
closers before the string boundary, preserving source order. Markdown
triple-backtick fences are emitted literally and do not put the lexer into
backtick-string state, so pair handling continues for code between the fences.
The plan requires keyboard and cursor-right capabilities and never uses
clipboard paste or revision evidence.
""",
    """Pair-aware behavior is restricted to `()`, `{}`, `[]`, `\"\"`, and `''`.
Python-style triple-quoted runs (`\"\"\"` and `'''`) are emitted as explicit
atoms at both boundaries and never use cursor-right because editors do not
reliably generate their three-character closing pair. Brackets inside
recognized strings and comments remain literal and never enter the pair stack;
an ordinary generated closing quote is still skipped once. A `//` comment
boundary applies the same line-leading generated-closer rule before Return is
emitted. Markdown triple-backtick fences and single backticks are literal and
do not put the lexer into backtick-string state, so pair handling continues for
code between fences. The plan requires keyboard and cursor-right capabilities
and never uses clipboard paste or revision evidence.
""",
)

replace_once(
    "docs/ARCHITECTURE.md",
    """It never reads focused-field text or window titles. On macOS, native controls
retain exact focused-element comparison. A focused element beneath an
`AXWebArea` is explicitly `RenderHostLimited`: the adapter compares the stable
frontmost process and focused top-level window while tolerating replacement of
the renderer's transient focus node. If a DOM-backed node does not expose a
traversable parent chain, web-only supported attribute names provide the
content-free classification; their values are never read. Shared render hosts
therefore may not expose exact logical-field identity within one window.
""",
    """It never reads focused-field text or window titles. On macOS, native controls
retain exact focused-element comparison. An initial focused element beneath an
`AXWebArea` selects a sticky `RenderHostLimited` session policy: the adapter
compares the stable frontmost process and focused top-level window while
tolerating replacement of the renderer's transient focus node, including a
replacement sample that briefly lacks the original web classification. If a
DOM-backed node does not expose a traversable parent chain, web-only supported
attribute names provide the initial content-free classification; their values
are never read. Process/window changes or missing stable window evidence still
stop, while logical-field changes inside one render-host window may remain
indistinguishable.
""",
)

replace_once(
    "docs/ARCHITECTURE.md",
    """The macOS target token contains only opaque process, focused-window, and
focused-element identity plus an `AXWebArea` classification bit. A bounded
Accessibility parent-role walk classifies web render hosts without requesting
titles, values, selection, or document text. Render-host sessions require the
same process and focused window throughout; native controls additionally
require the exact focused element.
""",
    """The macOS target token contains only opaque process, focused-window, and
focused-element identity plus an `AXWebArea` classification bit. A bounded
Accessibility parent-role walk classifies the initial web render host without
requesting titles, values, selection, or document text. That initial
classification selects a sticky process/window comparison policy so a rebuilt
same-window focus node may temporarily lose classification without stopping;
native controls continue to require the exact focused element.
""",
)

replace_once(
    "docs/PLATFORMS.md",
    """Use workspace/accessibility/window APIs only for target identity and
permission-safe focus evidence. Do not inspect focused text or window titles.
Native controls use exact focused-element identity. For an `AXWebArea`
render host, use stable process plus focused-window identity because editors
such as Monaco may rebuild their focused Accessibility node during normal
typing. If a Chromium editor does not expose a traversable `AXWebArea` parent
chain, support for the web-only `AXDOMIdentifier` or `AXDOMClassList` attribute
name supplies the same classification without reading either value. A
process/window change or evidence loss still stops safely; logical field
changes within one web render surface may be indistinguishable. The fixed
bridge returns only content-free session categories and counters.
""",
    """Use workspace/accessibility/window APIs only for target identity and
permission-safe focus evidence. Do not inspect focused text or window titles.
Native controls use exact focused-element identity. An initial `AXWebArea`
render-host classification selects stable process plus focused-window identity
for the session because Monaco may rebuild its focused Accessibility node
during normal typing. If a Chromium editor does not expose a traversable
`AXWebArea` parent chain, support for the web-only `AXDOMIdentifier` or
`AXDOMClassList` attribute name supplies the initial classification without
reading either value. A later same-window node may temporarily lose that
classification without looking like a target change. A process/window change,
missing stable window identity, disappearance, or capture failure still stops
safely; logical field changes within one web render surface may be
indistinguishable. The fixed bridge returns only content-free categories and
counters.
""",
)

replace_once(
    "docs/PLATFORMS.md",
    """macOS release requires code signing/notarization planning before claiming
general availability. The P4 arm64 `.app` is also available in
`v0.2.0-beta.2` as a clearly labelled ad-hoc testing preview; it is not a
Universal 2, Developer ID, notarized, or general public macOS release.
""",
    """macOS release requires code signing/notarization planning before claiming
general availability. The unreleased `v0.2.0-beta.3` candidate prepares a
clearly labelled additive arm64 testing preview built on an Apple Silicon
runner; `v0.2.0-beta.2` remains immutable. The preview is ad-hoc signed and is
not a Universal 2, Developer ID, notarized, Gatekeeper-ready, or general public
macOS release. Publication remains blocked until the repository's physical
release evidence is complete.
""",
)

replace_once(
    "docs/SECURITY_PRIVACY.md",
    """Code mode reads the current clipboard text and uses the keyboard adapter. It
skips source indentation and emits cursor-right actions for matching ordinary
pairs the editor is expected to have generated. Python-style triple-quoted
boundaries are emitted explicitly rather than assumed to be editor-generated.
Markdown triple-backtick fences are likewise emitted literally without reading
the fenced content. It does not use Clipboard paste or a revision-guarded paste
transaction. It does not add a second clipboard storage path or read destination
content.
""",
    """Code mode transiently reads the current clipboard source after an explicit
trigger and uses only the keyboard adapter for delivery. It never invokes
Paste, changes clipboard ownership, or creates a second clipboard storage path.
Pair navigation is limited to `()`, `{}`, `[]`, `\"\"`, and `''`; brackets in
strings/comments are literal, and triple-quote boundaries are explicit.
Markdown fences and single backticks are literal. The source exists only in the
bounded active plan/worker lifetime and is never logged, persisted, hashed,
transmitted, or exposed through Flutter/Swift status channels. Code mode never
reads destination content.
""",
)

replace_once(
    "docs/SECURITY_PRIVACY.md",
    """Before native dispatch, and between keyboard batches, ClipType re-captures
evidence and compares it with the original. It stops when the target changed,
disappeared, became ambiguous, or lost detail required by the original
guarantee. On macOS, native controls require exact focused-element identity;
an `AXWebArea` renderer uses same-process and same-focused-window evidence so a
content-free transient AX node rebuild is not mistaken for a target change.
Render-host fallback detection examines only the list of supported
Accessibility attribute names; it never reads DOM identifiers, class lists,
field values, or document content.
""",
    """Before native dispatch, and between keyboard actions/batches, ClipType
re-captures evidence and compares it with the original. It stops when the
target process/window changed, disappeared, or lost stable identity required by
the original guarantee. On macOS, native controls require exact
focused-element identity. An initial `AXWebArea` renderer classification
selects a sticky same-process and same-focused-window policy for that session,
so a rebuilt same-window node is not mistaken for a target change even if its
later sample briefly lacks web classification. Render-host detection examines
only supported Accessibility attribute names; it never reads DOM identifier
values, class-list values, field values, selections, titles, or document
content.
""",
)

replace_once(
    "docs/TESTING.md",
    """- Code mode's FIFO keyboard actions, leading-indentation stripping, same-line
  and line-leading pair skipping, explicit triple-quoted boundaries, and
  string/comment handling;
""",
    """- Code mode's FIFO keyboard-only actions, five bounded pair families,
  leading-indentation stripping, same-line and line-leading pair skipping,
  comment-boundary closing-line navigation, literal string/comment brackets,
  explicit triple-quoted boundaries, and long-tail completion;
""",
)

replace_once(
    "docs/COMPATIBILITY.md",
    "ClipType `v0.1.0-beta.1` is the first public Windows x86_64 beta. The compatibility promise is evidence-based and narrower than “all Windows applications.”\n",
    "ClipType `v0.2.0-beta.3` is the current unreleased candidate. Windows x86_64 remains the primary beta channel, with a proposed additive macOS arm64 testing preview. Publication remains blocked by the open physical evidence gate. The compatibility promise is evidence-based and narrower than “all applications.”\n",
)

replace_once(
    "docs/COMPATIBILITY.md",
    """| `code` | Sends bounded keyboard actions, skips leading indentation, and uses right-arrow navigation for matching auto-generated ordinary delimiters/quotes. A line-leading closer crosses the editor-generated line and its indentation instead of inserting a duplicate Return. Python-style triple-quoted boundaries (`\"\"\"`, `'''`) and Markdown triple-backtick fences are typed explicitly. It assumes editor auto-pair and auto-indent are enabled for ordinary pairs. |
""",
    """| `code` | Separate keyboard-only backend; Paste is unavailable by design. Pair-aware behavior is limited to `()`, `{}`, `[]`, `\"\"`, and `''`. Matching source closers skip editor-generated closers; line-leading closers, including after `//` comments, cross the editor-generated closing line without a duplicate Return. Brackets in strings/comments, triple quotes, Markdown fences, and single backticks are literal. It assumes ordinary auto-pair and auto-indent are enabled. |
""",
)

replace_once(
    "docs/COMPATIBILITY.md",
    """ClipType captures and revalidates non-content destination evidence. Native
controls can usually be distinguished. On macOS, an `AXWebArea` render host is
tracked by frontmost process plus focused top-level window so transient Monaco
focus-node replacement does not look like a target switch. Switching process
or window still stops. Multiple logical fields inside one shared render
surface may remain indistinguishable, so ClipType does not claim an exact
logical-field or caret guarantee there.
""",
    """ClipType captures and revalidates non-content destination evidence. Native
controls can usually be distinguished. On macOS, an initial `AXWebArea`
classification selects a sticky frontmost-process plus focused-window policy,
so repeated Monaco focus-node replacement in the same window, including a
temporarily unclassified replacement node, does not look like a target switch.
Switching process/window or losing stable window evidence still stops before
the next action. Multiple logical fields inside one shared render surface may
remain indistinguishable, so ClipType does not claim an exact logical-field or
caret guarantee there.
""",
)

replace_once(
    "docs/COMPATIBILITY.md",
    """Clipboard mode leaves all formats unchanged and invokes ordinary paste. Code
mode uses Unicode keyboard events and right-arrow navigation, including
line-end navigation for generated closing lines, so it is intended
for text editors with ordinary auto-pair and auto-indent enabled. Python-style
triple-quoted boundaries are sent explicitly because they are not reliably
auto-completed; Markdown triple-backtick fences are literal boundaries and
pair handling continues inside them. Rich targets may
prefer HTML, RTF, image, or application-specific formats already present beside
`CF_UNICODETEXT`; use Clipboard mode for those formats.
""",
    """Clipboard mode leaves all formats unchanged and invokes ordinary paste. Code
mode uses only Unicode keyboard/key-navigation events and is intended for text
editors with ordinary auto-pair and auto-indent enabled. Its pair grammar is
limited to `()`, `{}`, `[]`, `\"\"`, and `''`; string/comment brackets and
single backticks are literal, while triple-quoted boundaries are sent
explicitly. Markdown fences are literal boundaries and pair handling continues
inside them. Rich targets may prefer HTML, RTF, image, or application-specific
formats already present beside `CF_UNICODETEXT`; use Clipboard mode for those
formats.
""",
)

replace_once(
    "docs/COMPATIBILITY.md",
    """The current public-beta candidate remains blocked by Issue #41 until Chinese input reliability, per-action pacing, tray controls, and a replacement exact-SHA interactive validation are complete. Earlier Issue #33 beta-ready wording is superseded and must not be used as a release authorization.
""",
    """The `v0.2.0-beta.3` candidate remains blocked by Issue #41 until the replacement exact-SHA physical validation reconciles Issue #33. Automated Code-mode, Windows, and hosted macOS evidence does not authorize merge, tag, signing, publication, or a broad compatibility claim by itself.
""",
)

replace_once(
    "docs/RELEASE.md",
    """The P4 macOS Flutter runner remains an arm64 candidate gate. Its PR/manual
quality gate is `.github/workflows/p4-macos-arm64.yml`; that workflow does not
publish an artifact and does not replace the separate Universal 2,
Developer ID, notarization, and stapling requirements for a general public
macOS release. `v0.2.0-beta.2` additionally carries a manually validated,
clearly labelled arm64 testing preview from the exact release source.
""",
    """The P4 macOS Flutter runner remains an arm64 testing-preview gate. Its
PR/manual quality gate is `.github/workflows/p4-macos-arm64.yml`. The beta.3
candidate builds the exact source on Apple Silicon, installs and launch-smokes
`/Applications/ClipType.app`, packages arm64-only ZIP/DMG assets, and records
checksums. Any later attachment must be additive, use the exact immutable tag,
and refuse existing asset names. This does not replace the Universal 2,
Developer ID, notarization, stapling, Gatekeeper, physical Accessibility, or
real-editor requirements. Publication remains blocked by Issue #41 and
`v0.2.0-beta.2` remains immutable.
""",
)

replace_once(
    "docs/phases/P4_MACOS_ARM64_LOCAL.md",
    "- Release status: arm64 testing preview attached to `v0.2.0-beta.2`; not a general public macOS beta\n",
    "- Release status: beta.3 arm64 testing-preview candidate; publication blocked pending physical evidence\n",
)

replace_once(
    "docs/phases/P4_MACOS_ARM64_LOCAL.md",
    """## Release boundary

This phase may produce a local `.app` for inspection. It must not be described
as `MACOS ARM64 BETA READY` without the physical and release evidence listed
above. No push, merge, tag, release publication, Apple credential, or
notarization action is part of this local track.
""",
    """## Release boundary

This phase may produce a local or hosted arm64 `.app` testing preview. The
beta.3 candidate workflow may build, install, launch-smoke, and retain versioned
ad-hoc ZIP/DMG artifacts. It must not publish or be described as `MACOS ARM64
BETA READY` without the physical evidence listed above and repository release
authorization. Developer ID, notarization, stapling, Gatekeeper acceptance,
Universal 2, Intel/Rosetta, persistent Accessibility consent, and real VS
Code/Monaco input are not inferred from hosted launch smoke.
""",
)

replace_once(
    "docs/adr/0018-macos-render-host-target-evidence.md",
    "- Status: Accepted\n",
    "- Status: Superseded by ADR-0020\n",
)

replace_once(
    "docs/adr/README.md",
    "- [`ADR-0018`](0018-macos-render-host-target-evidence.md) — Use stable process/window evidence for macOS `AXWebArea` render hosts.\n",
    "- [`ADR-0018`](0018-macos-render-host-target-evidence.md) — Superseded initial stable process/window evidence for macOS render hosts.\n- [`ADR-0019`](0019-code-mode-bounded-pair-contexts.md) — Restrict Code-mode pairing to five source-context-safe pair families.\n- [`ADR-0020`](0020-macos-render-host-sticky-session.md) — Keep initial macOS render-host process/window classification sticky for a session.\n",
)

replace_once(
    "docs/releases/v0.2.0-beta.3.md",
    "Release date: 2026-09-05\n\n`v0.2.0-beta.3` is a new, non-overwriting prerelease.",
    "Candidate prepared: 2026-09-05\n\n`v0.2.0-beta.3` is prepared as a new, non-overwriting prerelease candidate.",
)
